In [1]:
import kagglehub
path = kagglehub.dataset_download("aiexplorer77/internship-selection-prediction-dataset")

Downloading to /root/.cache/kagglehub/datasets/aiexplorer77/internship-selection-prediction-dataset/1.archive...

100%|██████████| 164k/164k [00:00<00:00, 456kB/s]

Extracting files...

In [2]:
#Locating the CSV
import os
print(os.listdir(path))

['Internship_Selection_Dataset.csv']

In [3]:
#Loading into Pandas
import pandas as pd
file_path=os.path.join(path,"Internship_Selection_Dataset.csv")
df=pd.read_csv(file_path)
df.head()

,student_id,CGPA,skills_score,projects_count,internships_done,communication_score,aptitude_score,coding_test_score,resume_score,extracurricular,...,hackathons_participated,certifications_count,linkedin_activity_score,github_score,soft_skills_score,interview_score,consistency_score,backlogs,placement_training,selected
0,1,6.87,7,0,0,4,3,2,7,Yes,...,0,7,5,9,3,1,4,4,Yes,1
1,2,9.75,4,4,2,3,3,6,1,Yes,...,3,2,8,8,3,9,8,5,Yes,1
2,3,8.66,2,1,1,2,1,4,6,Yes,...,4,1,5,2,2,1,3,2,Yes,1
3,4,7.99,5,4,2,8,8,10,8,No,...,1,5,5,9,2,7,10,1,Yes,1
4,5,5.78,3,2,2,4,9,1,7,Yes,...,4,7,3,8,7,8,6,5,Yes,1

In [4]:
#Find how many selected and how many not
df['selected'].value_counts()

selected
1    7374
0    2626
Name: count, dtype: int64

In [6]:
#Checking if any cleaning needed
print("College Tiers:", df['college_tier'].unique())
print("Extracurriculars:", df['extracurricular'].unique())
print("Placement Training:", df['placement_training'].unique())

College Tiers: ['Tier 2' 'Tier 3' 'Tier 1']
Extracurriculars: ['Yes' 'No']
Placement Training: ['Yes' 'No']

In [10]:
#Binary Mapping
binary_mapping = {'Yes': 1, 'No':0}
df['extracurricular'] = df['extracurricular'].map(binary_mapping)
df['placement_training'] = df['placement_training'].map(binary_mapping)
df.head()

,student_id,CGPA,skills_score,projects_count,internships_done,communication_score,aptitude_score,coding_test_score,resume_score,extracurricular,...,hackathons_participated,certifications_count,linkedin_activity_score,github_score,soft_skills_score,interview_score,consistency_score,backlogs,placement_training,selected
0,1,6.87,7,0,0,4,3,2,7,1,...,0,7,5,9,3,1,4,4,1,1
1,2,9.75,4,4,2,3,3,6,1,1,...,3,2,8,8,3,9,8,5,1,1
2,3,8.66,2,1,1,2,1,4,6,1,...,4,1,5,2,2,1,3,2,1,1
3,4,7.99,5,4,2,8,8,10,8,0,...,1,5,5,9,2,7,10,1,1,1
4,5,5.78,3,2,2,4,9,1,7,1,...,4,7,3,8,7,8,6,5,1,1

In [7]:
#Tier Mapping
tier_mapping = {'Tier 1': 1, 'Tier 2': 2, 'Tier 3': 3}
df['college_tier'] = df['college_tier'].map(tier_mapping)
df.head()

,student_id,CGPA,skills_score,projects_count,internships_done,communication_score,aptitude_score,coding_test_score,resume_score,extracurricular,...,hackathons_participated,certifications_count,linkedin_activity_score,github_score,soft_skills_score,interview_score,consistency_score,backlogs,placement_training,selected
0,1,6.87,7,0,0,4,3,2,7,Yes,...,0,7,5,9,3,1,4,4,Yes,1
1,2,9.75,4,4,2,3,3,6,1,Yes,...,3,2,8,8,3,9,8,5,Yes,1
2,3,8.66,2,1,1,2,1,4,6,Yes,...,4,1,5,2,2,1,3,2,Yes,1
3,4,7.99,5,4,2,8,8,10,8,No,...,1,5,5,9,2,7,10,1,Yes,1
4,5,5.78,3,2,2,4,9,1,7,Yes,...,4,7,3,8,7,8,6,5,Yes,1

In [11]:
#Correlation Matrix
correlations = df.corr()['selected'].sort_values(ascending=False)
print(correlations)

selected                   1.000000
interview_score            0.069152
skills_score               0.058453
communication_score        0.044100
soft_skills_score          0.041482
resume_score               0.036477
projects_count             0.035092
coding_test_score          0.035067
github_score               0.031460
internships_done           0.029197
extracurricular            0.027474
consistency_score          0.027301
CGPA                       0.027016
certifications_count       0.025724
aptitude_score             0.024051
placement_training         0.019435
hackathons_participated    0.008805
linkedin_activity_score    0.000236
student_id                -0.005582
college_tier              -0.018090
backlogs                  -0.038708
Name: selected, dtype: float64

In [12]:
#Exporting to CSV
df.to_csv('cleaned_internship_data.csv', index=False)